# Generated by Django 3.0.7 on 2020-06-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.IntegerField(unique=True, verbose_name='Course Number')),
                ('title', models.CharField(max_length=60, verbose_name='Course')),
                ('instructorName', models.CharField(db_column="Instructor's Name", default='', max_length=80, verbose_name="Instructor's Name")),
                ('duration', models.FloatField(choices=[(0.5, 'short'), (2, 'longer'), (1, 'normal'), (1.5, 'long')], db_column='Class Duration', help_text='Pick short for .5 hours, normal for 1 hour, long for 1.5 hours,or longer for 2 hours.', verbose_name='Course Duration')),
            ],
        ),
    ]
