# Generated by Django 3.0.7 on 2020-06-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='courseNumber',
            field=models.IntegerField(verbose_name='Course Number'),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='duration',
            field=models.FloatField(choices=[(2, 'longer'), (0.5, 'short'), (1.5, 'long'), (1, 'normal')], db_column='Class Duration', help_text='Pick short for .5 hours, normal for 1 hour, long for 1.5 hours,or longer for 2 hours.', verbose_name='Course Duration'),
        ),
    ]
